#!/bin/bash

# Synopsis:
# Insert data from 'error_data.csv' into check constrained tables and save results to 'check_errors.csv'.
# The csv can than be imported into the tests table to be shown to students.

# Arguments:
# $1: exercise slug

# Output:
# Writes the test results to a check_errors.csv file.

slug=$1
snake_slug=$(echo "${slug}" | sed 's/-/_/g')

# prepare input file:
cat ./create_fixture.sql > temp_sql_input.sql
printf "\n" >> temp_sql_input.sql
cat "./${slug}.sql" >> temp_sql_input.sql

rm check_errors.csv -f
while IFS=, read -r uuid name column insert
do
    status="pass"
    message=""
    task_id=0
    test_code=""
    output=""
    test_code="INSERT INTO ${snake_slug} (${column}) VALUES ('${insert}');"
    sqlite_output=$(sqlite3 '' --init temp_sql_input.sql -bail  "${test_code}" ".exit" 2>&1)
    if [ $? -eq 0 ] 
    then
        status="fail"
        message="${insert} should not be inserted into the table"
    fi
    # import exptects 9 values:
    echo "${uuid},${name},${status},${message},${output},${test_code},${task_id},," >> check_errors.csv
done < error_data.csv

# cleanup
rm temp_sql_input.sql -f
