UPDATE pangram
   SET result = (
         INSTR(LOWER(sentence), 'a')
     AND INSTR(LOWER(sentence), 'b')
     AND INSTR(LOWER(sentence), 'c')
     AND INSTR(LOWER(sentence), 'd')
     AND INSTR(LOWER(sentence), 'e')
     AND INSTR(LOWER(sentence), 'f')
     AND INSTR(LOWER(sentence), 'g')
     AND INSTR(LOWER(sentence), 'h')
     AND INSTR(LOWER(sentence), 'i')
     AND INSTR(LOWER(sentence), 'j')
     AND INSTR(LOWER(sentence), 'k')
     AND INSTR(LOWER(sentence), 'l')
     AND INSTR(LOWER(sentence), 'm')
     AND INSTR(LOWER(sentence), 'n')
     AND INSTR(LOWER(sentence), 'o')
     AND INSTR(LOWER(sentence), 'p')
     AND INSTR(LOWER(sentence), 'q')
     AND INSTR(LOWER(sentence), 'r')
     AND INSTR(LOWER(sentence), 's')
     AND INSTR(LOWER(sentence), 't')
     AND INSTR(LOWER(sentence), 'u')
     AND INSTR(LOWER(sentence), 'v')
     AND INSTR(LOWER(sentence), 'w')
     AND INSTR(LOWER(sentence), 'x')
     AND INSTR(LOWER(sentence), 'y')
     AND INSTR(LOWER(sentence), 'z')
   );
