-- Schema: CREATE TABLE "space-age" (
--             planet  TEXT    NOT NULL,
--             seconds INTEGER NOT NULL,
--             result  TEXT                -- json object
--         );
-- Task: update the space-age table and set the result based on planet
--       and seconds.
--       * the result column should contain JSON-encoded data: an
--         object with the age as double or a description of any
--         errors.
