-- Schema:
-- CREATE TABLE sieve (
--   "limit" INTEGER NOT NULL,
--   result  TEXT
-- );
--
-- Task: update the sieve table and set the result column based on the limit.
--       * the result column must be filled with a string of prime numbers separated by ", ". Example: 2, 3.
